flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/astanin/moo.git
    commit: ce77e5ac1a1e370746a60ee21f67f50cc5b85b98
extra-deps:
- moo-1.1
- gray-code-0.3.1
- monad-mersenne-random-0.1
resolver: lts-1.15
