flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- MonadRandom-0.5.1
- fail-4.9.0.0
- mtl-2.2.1
- primitive-0.6.2.0
- random-1.1
- random-shuffle-0.0.4
- transformers-compat-0.5.1.4
resolver: ghc-8.0.1
